language: php

php:
  - 5.5
  - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.1.0"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction
# codeception
  - travis_retry composer global require "codeception/codeception:^2.0" "codeception/specify" "codeception/verify"
# setup application:
  - |
    cp .env.dist .env
    cp vhost.conf.dist vhost.conf
    sed -i s/yii2-starter-kit\.dev/localhost:8080/ .env

  - |
    cd tests/codeception/backend && codecept build
    cd ../common && codecept build
    cd ../console && codecept build
    cd ../frontend && codecept build
    cd ../../../

before_script:
  - mysql -e 'CREATE DATABASE `yii2-starter-kit`;';
  - php tests/codeception/bin/yii app/setup --interactive=0

script:
  - |
    php -S localhost:8080 > /dev/null 2>&1 &
    cd tests
    ./../vendor/bin/codecept run --debug